name: Build the Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup node.jc
        uses: actions/setup-node@v4
        with:
          node-version: '22'
            
      - name: Install dependencies
        run: npm ci

      - name: Format Frontend
        run: npm run format

      - name: Build Frontend
        run: npm run build
